### ISSUE TITLE
Open lvproj in correct labview version

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/build-support#25]
- 32/64 bit
- 2019, 2020, etc

Use Dragon config?

#### .dragon\settings.toml:

```toml
[labview]
version = 2019
bitness = 64

```

#### *.dragon:
```toml
[project]
labview-version = 2019
```
